spring:
  profiles:
    active: dev
  datasource:
    hikari:
      username: bootuser
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mariadb://localhost:3307/bootex?characterEncoding=UTF-8&serverTimezone=UTC
      password: mariadb 
      allow-pool-suspension: 'true'
      connection-test-query: SELECT 1      
  jpa:
    hibernate:
      use-new-id-generator-mappings: 'false'
      ddl-auto: update
    properties:
      hibernate:
        show-sql: 'true'
        format_sql: 'true'
    database-platform: org.hibernate.dialect.MariaDB103Dialect
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
  thymeleaf:
    cache: 'false'
  web:
    resources:
      cache:
        period: '0'
server:
  port: '8088'
        
mybatis:
  mapper-locations: classpath:/mappers/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: 'true'
logging:
  config: classpath:logback-${spring.profiles.active}.xml
